language: elixir
elixir:
  - 1.3.4

otp_release:
  - 19.0

addons:
  postgresql: '9.4'

before_install:
  - mix local.hex --force

install:
  - cd api/
  - mix deps.get
  - mix do ecto.create, ecto.migrate

script:
  - mix dogma
  - mix test
